ti-edgeai: BBMASK for component edgeai-init
Issue: LIN1023-3069

BBMASK edgeai-init.bb since it's not used for WRLinux yet.
To avoid below layer check error:

ERROR: Nothing RPROVIDES 'edgeai-gui-app' (but meta-edgeai/recipes-tisdk/edgeai-components/edgeai-init.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'edgeai-gui-app' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['edgeai-gui-app']
ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'edgeai-init', 'edgeai-gui-app']

(LOCAL REV: NOT UPSTREAM) - Wrlinux specific

Signed-off-by: Xulin Sun <xulin.sun@windriver.com>